### ISSUE TITLE
Release New Version with Bugfixes

### ISSUE THREAD

**Issue by jaywilliams** [roots/wp-h5bp-htaccess#15]
After installing v2.0.0, as recommended by the readme, I came across the reference error, which was fixed in https://github.com/roots/wp-h5bp-htaccess/commit/82873f53213ba7f726a05791b38f6a7c937c62fa.

Are there any plans to release a minor point update or will I have to run off of dev-master in my composer.json file?

**Comment by QWp6t** [comment]
i think @retlehs has to do that.

**Comment by QWp6t** [comment]
Done.

there is one other commit since the tag, but the differences between 2.0.1 and current master are cosmetic. i just forgot to update the readme before tagging the release.

**Comment by jaywilliams** [comment]
Excellent, thanks!
