### ISSUE TITLE
Add rules to secure wp-includes?

### ISSUE THREAD

**Issue by QWp6t** [roots/wp-h5bp-htaccess#6]
It could be done with the RewriteEngine as in the example below, or it could be done with FilesMatch.

But we would have to take into account that users don't always install WordPress into their root directory, which complicates things. We could also use the typical {{double-brackets}} syntax to indicate a dynamic value, and then use PHP to determine it and change the value before adding to .htaccess file.

> ## Securing wp-includes ##
> A second layer of protection can be added where scripts are generally not intended to be accessed by any user. One way to do that is to block those scripts using mod_rewrite in the .htaccess file. Note: to ensure the code below is not overwritten by WordPress, place it outside the # BEGIN WordPress and # END WordPress tags in the .htaccess file. WordPress can overwrite anything between these tags.
> 
> ```
# Block the include-only files.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^wp-admin/includes/ - [F,L]
RewriteRule !^wp-includes/ - [S=3]
RewriteRule ^wp-includes/[^/]+\.php$ - [F,L]
RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F,L]
RewriteRule ^wp-includes/theme-compat/ - [F,L]
</IfModule>
```
> Note that this won't work well on Multisite, as `RewriteRule ^wp-includes/[^/]+\.php$ - [F,L]` would prevent the ms-files.php file from generating images. Omitting that line will allow the code to work, but offers less security.

http://codex.wordpress.org/Hardening_WordPress#Securing_wp-includes

**Comment by retlehs** [comment]
closed by #11
